# Global Banned Functions
banned:
  - system
  - popen
  - gets
  - alloca
  - fopen
  - fclose
  - fread
  - fwrite
  - fprintf
  - fscanf
  - fgets
  - printf
  - scanf
  - puts
  - getchar
  - putchar
  - shutdown