name: Lab-2
root: .
discover:
    leaf_submission: true
    min_c_files: 1
compile:
    gcc: gcc
    flags:
        - -Wall
        - -Wextra
        - -lpthread
    source_file: S2.c
run:
    test_cases:
        - name: No args
          expected_exit: 0
